# Generated by Django 6.0.6 on 2026-07-07 05:28

import rag.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_business_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='api_key',
            field=models.CharField(default=rag.models.generate_api_key, editable=False, max_length=32, unique=True),
        ),
    ]
